### ISSUE TITLE
Unable to install certain mods, getting a runtime error.

### ISSUE THREAD

**Issue by AquaRush** [olegbl/d2rmm#17] opened 2024-03-30 18:09 UTC
# The issue

![image](https://github.com/olegbl/d2rmm/assets/25262287/766a6d08-9484-44c9-aa2e-298d7b4b2114)

## Name of mods

* Expanded Stash
* Increase Monster Density
* Merc Equip
* Terror Zones

## Information

Strangely, the D2RMM was working perfectly fine on the pirated version of D2R, the reason I say pirated is because first time I tried D2RMM with retail version, it simply threw a lot of errors and the game wasn't even starting, Nexusmod comments stated to re-install the game which I did not want to do as I've modded it a lot.

Fast forward a week, I decided to switch to retail version from pirated by manually saving all the modifications I've done and completely reinstalled the game moving it from the SSD directly onto the nVME `Local Disk (C:)`.
I also did a complete reinstall of D2RMM just to make everything as a fresh start and:
* I started D2R just to make sure it runs with D2RMM which it did.
* I then installed the mods into the folder of D2RMM called `mods`
* Out of 28, only 24 installed, 4 did not :(
* I tried extracting the data of D2R using CascViewer but that also did not solve the problem.
* Tried giving full admin permissions on all sub-folders along with permanently making D2R.exe to always run with Admin Rights just to make sure that Win system isn't somewhat blocking it.
* Found another user with similar problem stating that reinstalling the game fixed the issue for him but this is a fresh install and I don't feel like waiting another 2-3 hours to redownload and install the game.
* I've tried both `version 1.5.0` & `v1.6.0` and removing the saved games folder and reinstalling all the mods manually but it still throws the same error over and over.

Help is greatly appreciated, I was unable to export the full logs statement as GitHub would crash with all the overloaded information.

Thank you in advance for your assistance.

**Comment by olegbl** [comment] 2024-03-30 20:38
This error indicates that CascLib cannot read those files from the game's data:

https://github.com/olegbl/d2rmm/blob/c6310f766ae80c48b3557d42637bce939c89f29e/src/main/api.ts#L258-L271

Generally, that means something is wrong with your setup and you should be able to reproduce the issue using CascView.

The error code (11) means `ERROR_BAD_FORMAT` (https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/18d8fbe8-a967-4f1c-ae50-99ca8e491d2d) and implies that the file is corrupt.

For solutions:
1. Reinstalling the game *should* help.
2. You could also try extracting all the data with CascView and use "Pre-Extracted Data" instead of "Casc Archive" as "Game Data Source", though I think you'd run into the same issue.

Closing as this is not a bug (at least, not a D2RMM one.)

**Closed by olegbl** 2024-03-30 20:38 UTC

**Comment by AquaRush** [comment] 2024-03-31 07:21
> This error indicates that CascLib cannot read those files from the game's data:
> 
> https://github.com/olegbl/d2rmm/blob/c6310f766ae80c48b3557d42637bce939c89f29e/src/main/api.ts#L258-L271
> 
> Generally, that means something is wrong with your setup and you should be able to reproduce the issue using CascView.
> 
> The error code (11) means `ERROR_BAD_FORMAT` (https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/18d8fbe8-a967-4f1c-ae50-99ca8e491d2d) and implies that the file is corrupt.
> 
> For solutions:
> 
> 1. Reinstalling the game _should_ help.
> 2. You could also try extracting all the data with CascView and use "Pre-Extracted Data" instead of "Casc Archive" as "Game Data Source", though I think you'd run into the same issue.
> 
> Closing as this is not a bug (at least, not a D2RMM one.)

I have solved the issue, for future reference in case someone else struggles with the same issue as I did, CascViewer both x86/x64 (latest version and hivework version) gave me an error upon extraction, @olegbl was right that files seem to be corrupt because CascViewer could not extract all the data.

The issue comes from admin privileges, if you install it in the default path `Local Disk (C:)`, uninstalling the game and installing to another nVME (say `Local Disk (E:)` did the job and I didn't even have to extract the data using CascViewer.

Thank you for the assistance @olegbl :)
