### ISSUE TITLE
*eol column for .txt files does not get pushed

### ISSUE THREAD

**Issue by Caedendi** [olegbl/d2rmm#15] opened 2024-02-27 20:52 UTC
Hey olegbl,

When pushing new entries to `.txt` files using `D2RMM.readTSV()` and `D2RMM.writeTSV()` the value for the `*eol` column is not pushed. I'm working on `itemstatcost.txt` and the problem does not occur for the `*ID` column.

I loaned/edited the below code from [here](https://www.nexusmods.com/diablo2resurrected/mods/449) as an example:

`mod.json`
```
{
  "name": "Act3 Quest Skip Cube Recipe",
  "description": "Adds additional cube recipe to access Durance of Hate and Quest Skip.",
  "author": "OGGamerDude",
  "website": "https://www.nexusmods.com/diablo2resurrected/mods/449",
  "version": "1.0"
}
```

`mod.js`
```
let FILE_PATH_CUBEMAIN = "global\\excel\\cubemain.txt";
let file = D2RMM.readTsv(FILE_PATH_CUBEMAIN);

file.rows.push({
  description: "Khalim's Flail -> Khalim's Will",
  enabled: 1,
  version: 100,
  numinputs: 1,
  "input 1": "qf1",
  output: "qf2",
  "*eol": 0,
});

D2RMM.writeTsv(FILE_PATH_CUBEMAIN, file);
```

Do you have any idea why and how to fix this? 

_(I know this column is not used for gameplay, but I'm currently trying to port an existing mod and I want the result to be identical.)_

**Comment by olegbl** [comment] 2024-02-27 20:56
Duplicate of #1.

**Closed by olegbl** 2024-02-27 20:56 UTC
