### ISSUE TITLE
TSV not save the last column

### ISSUE THREAD

**Issue by qhu91it** [olegbl/d2rmm#2] opened 2022-04-19 21:25 UTC
For example glovesHeight is the last column of inventory
```js
const inventoryFilename = 'global\\excel\\inventory.txt';
const inventory = D2RMM.readTsv(inventoryFilename);
inventory.rows.forEach((row) => {
    row.glovesHeight = 53;
});
D2RMM.writeTsv(inventoryFilename, inventory);
```
Open inventory.txt and see glovesHeight is not change.

**Comment by olegbl** [comment] 2022-04-19 21:34
Duplicate of #1

**Closed by olegbl** 2022-04-19 21:34 UTC
